import { NextResponse } from "next/server"

// Dados detalhados de exemplo de alunos para a API fake do Moodle
const studentsDetailed = [
  {
    id: "1001",
    name: "Alex Johnson",
    email: "alex.johnson@example.com",
    phone: "(555) 123-4567",
    program: "Ciência da Computação",
    yearLevel: "3º Ano",
    enrollmentDate: "1 Set, 2022",
    creditsCompleted: 68,
    academicStanding: "Boa Situação",
    advisor: "Dra. Sarah Chen",
    attendance: 65,
    assignmentCompletion: 58,
    averageGrade: 72,
    riskLevel: "high",
    lastLogin: "3 dias atrás",
    courses: [
      {
        id: 1,
        name: "Introdução à Ciência da Computação",
        code: "CS101",
        instructor: "Dr. James Wilson",
        credits: 3,
        schedule: "Seg/Qua 10:00",
        grade: 78,
        lastActivity: "2 dias atrás",
      },
      {
        id: 2,
        name: "Estruturas de Dados e Algoritmos",
        code: "CS201",
        instructor: "Dra. Emily Rodriguez",
        credits: 4,
        schedule: "Ter/Qui 13:00",
        grade: 65,
        lastActivity: "5 dias atrás",
      },
      {
        id: 3,
        name: "Sistemas de Banco de Dados",
        code: "CS301",
        instructor: "Dr. Michael Brown",
        credits: 3,
        schedule: "Qua/Sex 15:00",
        grade: 58,
        lastActivity: "1 semana atrás",
      },
      {
        id: 4,
        name: "Desenvolvimento Web",
        code: "CS401",
        instructor: "Profa. Lisa Zhang",
        credits: 3,
        schedule: "Seg/Sex 9:00",
        grade: 72,
        lastActivity: "3 dias atrás",
      },
    ],
  },
  {
    id: "1002",
    name: "Samantha Lee",
    email: "samantha.lee@example.com",
    phone: "(555) 234-5678",
    program: "Ciência da Computação",
    yearLevel: "2º Ano",
    enrollmentDate: "1 Set, 2023",
    creditsCompleted: 32,
    academicStanding: "Boa Situação",
    advisor: "Dr. Robert Johnson",
    attendance: 78,
    assignmentCompletion: 82,
    averageGrade: 76,
    riskLevel: "medium",
    lastLogin: "Ontem",
    courses: [
      {
        id: 1,
        name: "Introdução à Ciência da Computação",
        code: "CS101",
        instructor: "Dr. James Wilson",
        credits: 3,
        schedule: "Seg/Qua 10:00",
        grade: 85,
        lastActivity: "Ontem",
      },
      {
        id: 2,
        name: "Estruturas de Dados e Algoritmos",
        code: "CS201",
        instructor: "Dra. Emily Rodriguez",
        credits: 4,
        schedule: "Ter/Qui 13:00",
        grade: 72,
        lastActivity: "2 dias atrás",
      },
      {
        id: 5,
        name: "Redes de Computadores",
        code: "CS202",
        instructor: "Dr. David Kim",
        credits: 3,
        schedule: "Ter/Qui 15:00",
        grade: 78,
        lastActivity: "Ontem",
      },
      {
        id: 6,
        name: "Engenharia de Software",
        code: "CS203",
        instructor: "Profa. Jennifer Park",
        credits: 3,
        schedule: "Qua/Sex 11:00",
        grade: 68,
        lastActivity: "3 dias atrás",
      },
    ],
  },
  {
    id: "1003",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    phone: "(555) 345-6789",
    program: "Engenharia da Computação",
    yearLevel: "4º Ano",
    enrollmentDate: "1 Set, 2021",
    creditsCompleted: 98,
    academicStanding: "Lista do Reitor",
    advisor: "Dra. Lisa Thompson",
    attendance: 92,
    assignmentCompletion: 95,
    averageGrade: 88,
    riskLevel: "low",
    lastLogin: "Hoje",
    courses: [
      {
        id: 7,
        name: "Algoritmos Avançados",
        code: "CS401",
        instructor: "Dr. Thomas Lee",
        credits: 4,
        schedule: "Seg/Qua 14:00",
        grade: 92,
        lastActivity: "Hoje",
      },
      {
        id: 8,
        name: "Aprendizado de Máquina",
        code: "CS402",
        instructor: "Dra. Maria Garcia",
        credits: 4,
        schedule: "Ter/Qui 10:00",
        grade: 88,
        lastActivity: "Ontem",
      },
      {
        id: 9,
        name: "Computação Gráfica",
        code: "CS403",
        instructor: "Prof. John Smith",
        credits: 3,
        schedule: "Qua/Sex 13:00",
        grade: 85,
        lastActivity: "2 dias atrás",
      },
      {
        id: 10,
        name: "Projeto Final",
        code: "CS499",
        instructor: "Dr. Robert Johnson",
        credits: 4,
        schedule: "Sex 15:00",
        grade: 90,
        lastActivity: "Hoje",
      },
    ],
  },
  {
    id: "1004",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@example.com",
    phone: "(555) 456-7890",
    program: "Ciência de Dados",
    yearLevel: "3º Ano",
    enrollmentDate: "1 Set, 2022",
    creditsCompleted: 64,
    academicStanding: "Boa Situação",
    advisor: "Dr. Michael Brown",
    attendance: 88,
    assignmentCompletion: 75,
    averageGrade: 82,
    riskLevel: "low",
    lastLogin: "Ontem",
    courses: [
      {
        id: 11,
        name: "Métodos Estatísticos",
        code: "DS301",
        instructor: "Dra. Sarah Chen",
        credits: 3,
        schedule: "Seg/Qua 11:00",
        grade: 85,
        lastActivity: "Ontem",
      },
      {
        id: 12,
        name: "Mineração de Dados",
        code: "DS302",
        instructor: "Dr. James Wilson",
        credits: 4,
        schedule: "Ter/Qui 14:00",
        grade: 78,
        lastActivity: "3 dias atrás",
      },
      {
        id: 13,
        name: "Análise de Big Data",
        code: "DS303",
        instructor: "Profa. Lisa Zhang",
        credits: 3,
        schedule: "Qua/Sex 9:00",
        grade: 80,
        lastActivity: "2 dias atrás",
      },
      {
        id: 14,
        name: "Aprendizado de Máquina para Ciência de Dados",
        code: "DS304",
        instructor: "Dr. Thomas Lee",
        credits: 4,
        schedule: "Seg/Sex 13:00",
        grade: 85,
        lastActivity: "Ontem",
      },
    ],
  },
  {
    id: "1005",
    name: "David Kim",
    email: "david.kim@example.com",
    phone: "(555) 567-8901",
    program: "Ciência da Computação",
    yearLevel: "1º Ano",
    enrollmentDate: "1 Set, 2024",
    creditsCompleted: 15,
    academicStanding: "Boa Situação",
    advisor: "Dra. Emily Rodriguez",
    attendance: 70,
    assignmentCompletion: 68,
    averageGrade: 74,
    riskLevel: "medium",
    lastLogin: "4 dias atrás",
    courses: [
      {
        id: 1,
        name: "Introdução à Ciência da Computação",
        code: "CS101",
        instructor: "Dr. James Wilson",
        credits: 3,
        schedule: "Seg/Qua 10:00",
        grade: 72,
        lastActivity: "5 dias atrás",
      },
      {
        id: 15,
        name: "Cálculo I",
        code: "MATH101",
        instructor: "Dra. Sarah Chen",
        credits: 4,
        schedule: "Ter/Qui 9:00",
        grade: 68,
        lastActivity: "4 dias atrás",
      },
      {
        id: 16,
        name: "Introdução à Programação",
        code: "CS102",
        instructor: "Prof. John Smith",
        credits: 3,
        schedule: "Qua/Sex 14:00",
        grade: 75,
        lastActivity: "3 dias atrás",
      },
      {
        id: 17,
        name: "Design de Lógica Digital",
        code: "CS103",
        instructor: "Dra. Lisa Thompson",
        credits: 3,
        schedule: "Seg/Sex 11:00",
        grade: 80,
        lastActivity: "1 semana atrás",
      },
    ],
  },
  // Novos alunos adicionados
  {
    id: "1006",
    name: "Ana Silva",
    email: "ana.silva@example.com",
    phone: "(555) 678-9012",
    program: "Engenharia de Software",
    yearLevel: "2º Ano",
    enrollmentDate: "1 Set, 2023",
    creditsCompleted: 35,
    academicStanding: "Boa Situação",
    advisor: "Dr. Carlos Mendes",
    attendance: 62,
    assignmentCompletion: 55,
    averageGrade: 68,
    riskLevel: "high",
    lastLogin: "5 dias atrás",
    courses: [
      {
        id: 18,
        name: "Programação Orientada a Objetos",
        code: "CS204",
        instructor: "Dr. Paulo Santos",
        credits: 4,
        schedule: "Seg/Qua 13:00",
        grade: 65,
        lastActivity: "6 dias atrás",
      },
      {
        id: 19,
        name: "Desenvolvimento Ágil",
        code: "SE201",
        instructor: "Profa. Carla Oliveira",
        credits: 3,
        schedule: "Ter/Qui 10:00",
        grade: 62,
        lastActivity: "1 semana atrás",
      },
      {
        id: 20,
        name: "Arquitetura de Software",
        code: "SE202",
        instructor: "Dr. Ricardo Almeida",
        credits: 3,
        schedule: "Qua/Sex 15:00",
        grade: 70,
        lastActivity: "4 dias atrás",
      },
      {
        id: 21,
        name: "Interação Humano-Computador",
        code: "SE203",
        instructor: "Dra. Mariana Costa",
        credits: 3,
        schedule: "Seg/Sex 8:00",
        grade: 75,
        lastActivity: "5 dias atrás",
      },
    ],
  },
  {
    id: "1007",
    name: "Pedro Oliveira",
    email: "pedro.oliveira@example.com",
    phone: "(555) 789-0123",
    program: "Sistemas de Informação",
    yearLevel: "3º Ano",
    enrollmentDate: "1 Set, 2022",
    creditsCompleted: 70,
    academicStanding: "Boa Situação",
    advisor: "Dra. Fernanda Lima",
    attendance: 85,
    assignmentCompletion: 80,
    averageGrade: 78,
    riskLevel: "medium",
    lastLogin: "2 dias atrás",
    courses: [
      {
        id: 22,
        name: "Gestão de Projetos de TI",
        code: "SI301",
        instructor: "Dr. Marcos Pereira",
        credits: 3,
        schedule: "Seg/Qua 9:00",
        grade: 82,
        lastActivity: "2 dias atrás",
      },
      {
        id: 23,
        name: "Segurança da Informação",
        code: "SI302",
        instructor: "Dr. Rafael Souza",
        credits: 4,
        schedule: "Ter/Qui 14:00",
        grade: 75,
        lastActivity: "3 dias atrás",
      },
      {
        id: 24,
        name: "Sistemas Distribuídos",
        code: "SI303",
        instructor: "Profa. Juliana Ferreira",
        credits: 3,
        schedule: "Qua/Sex 10:00",
        grade: 78,
        lastActivity: "Ontem",
      },
      {
        id: 25,
        name: "Inteligência de Negócios",
        code: "SI304",
        instructor: "Dr. André Santos",
        credits: 3,
        schedule: "Seg/Sex 15:00",
        grade: 76,
        lastActivity: "2 dias atrás",
      },
    ],
  },
  {
    id: "1008",
    name: "Juliana Santos",
    email: "juliana.santos@example.com",
    phone: "(555) 890-1234",
    program: "Ciência de Dados",
    yearLevel: "4º Ano",
    enrollmentDate: "1 Set, 2021",
    creditsCompleted: 95,
    academicStanding: "Lista do Reitor",
    advisor: "Dr. Roberto Alves",
    attendance: 95,
    assignmentCompletion: 98,
    averageGrade: 92,
    riskLevel: "low",
    lastLogin: "Hoje",
    courses: [
      {
        id: 26,
        name: "Visualização de Dados",
        code: "DS401",
        instructor: "Dra. Camila Rocha",
        credits: 3,
        schedule: "Seg/Qua 11:00",
        grade: 95,
        lastActivity: "Hoje",
      },
      {
        id: 27,
        name: "Aprendizado Profundo",
        code: "DS402",
        instructor: "Dr. Lucas Martins",
        credits: 4,
        schedule: "Ter/Qui 13:00",
        grade: 90,
        lastActivity: "Ontem",
      },
      {
        id: 28,
        name: "Processamento de Linguagem Natural",
        code: "DS403",
        instructor: "Profa. Beatriz Lima",
        credits: 3,
        schedule: "Qua/Sex 14:00",
        grade: 93,
        lastActivity: "Hoje",
      },
      {
        id: 29,
        name: "Projeto de Ciência de Dados",
        code: "DS499",
        instructor: "Dr. Gustavo Pereira",
        credits: 4,
        schedule: "Sex 10:00",
        grade: 94,
        lastActivity: "Ontem",
      },
    ],
  },
  {
    id: "1009",
    name: "Lucas Ferreira",
    email: "lucas.ferreira@example.com",
    phone: "(555) 901-2345",
    program: "Engenharia da Computação",
    yearLevel: "1º Ano",
    enrollmentDate: "1 Set, 2024",
    creditsCompleted: 12,
    academicStanding: "Boa Situação",
    advisor: "Dra. Carolina Silva",
    attendance: 60,
    assignmentCompletion: 65,
    averageGrade: 71,
    riskLevel: "high",
    lastLogin: "6 dias atrás",
    courses: [
      {
        id: 1,
        name: "Introdução à Ciência da Computação",
        code: "CS101",
        instructor: "Dr. James Wilson",
        credits: 3,
        schedule: "Seg/Qua 10:00",
        grade: 68,
        lastActivity: "1 semana atrás",
      },
      {
        id: 15,
        name: "Cálculo I",
        code: "MATH101",
        instructor: "Dra. Sarah Chen",
        credits: 4,
        schedule: "Ter/Qui 9:00",
        grade: 65,
        lastActivity: "6 dias atrás",
      },
      {
        id: 30,
        name: "Física I",
        code: "PHYS101",
        instructor: "Dr. Eduardo Costa",
        credits: 4,
        schedule: "Ter/Qui 15:00",
        grade: 72,
        lastActivity: "5 dias atrás",
      },
      {
        id: 31,
        name: "Introdução à Engenharia",
        code: "ENG101",
        instructor: "Prof. Henrique Dias",
        credits: 2,
        schedule: "Sex 13:00",
        grade: 78,
        lastActivity: "4 dias atrás",
      },
    ],
  },
  {
    id: "1010",
    name: "Mariana Costa",
    email: "mariana.costa@example.com",
    phone: "(555) 012-3456",
    program: "Sistemas de Informação",
    yearLevel: "2º Ano",
    enrollmentDate: "1 Set, 2023",
    creditsCompleted: 38,
    academicStanding: "Boa Situação",
    advisor: "Dr. Felipe Martins",
    attendance: 75,
    assignmentCompletion: 72,
    averageGrade: 76,
    riskLevel: "medium",
    lastLogin: "3 dias atrás",
    courses: [
      {
        id: 32,
        name: "Banco de Dados I",
        code: "SI201",
        instructor: "Dra. Patrícia Alves",
        credits: 4,
        schedule: "Seg/Qua 14:00",
        grade: 78,
        lastActivity: "3 dias atrás",
      },
      {
        id: 33,
        name: "Análise de Sistemas",
        code: "SI202",
        instructor: "Dr. Thiago Rocha",
        credits: 3,
        schedule: "Ter/Qui 11:00",
        grade: 75,
        lastActivity: "4 dias atrás",
      },
      {
        id: 34,
        name: "Programação Web",
        code: "SI203",
        instructor: "Profa. Renata Oliveira",
        credits: 3,
        schedule: "Qua/Sex 9:00",
        grade: 80,
        lastActivity: "2 dias atrás",
      },
      {
        id: 35,
        name: "Gestão da Informação",
        code: "SI204",
        instructor: "Dr. Bruno Santos",
        credits: 3,
        schedule: "Seg/Sex 16:00",
        grade: 72,
        lastActivity: "3 dias atrás",
      },
    ],
  },
  {
    id: "1011",
    name: "Rafael Almeida",
    email: "rafael.almeida@example.com",
    phone: "(555) 123-4567",
    program: "Ciência da Computação",
    yearLevel: "3º Ano",
    enrollmentDate: "1 Set, 2022",
    creditsCompleted: 65,
    academicStanding: "Boa Situação",
    advisor: "Dr. Marcelo Lima",
    attendance: 90,
    assignmentCompletion: 85,
    averageGrade: 84,
    riskLevel: "low",
    lastLogin: "Ontem",
    courses: [
      {
        id: 36,
        name: "Compiladores",
        code: "CS301",
        instructor: "Dr. Victor Pereira",
        credits: 4,
        schedule: "Seg/Qua 10:00",
        grade: 88,
        lastActivity: "Ontem",
      },
      {
        id: 37,
        name: "Inteligência Artificial",
        code: "CS302",
        instructor: "Dra. Cristina Oliveira",
        credits: 4,
        schedule: "Ter/Qui 13:00",
        grade: 85,
        lastActivity: "2 dias atrás",
      },
      {
        id: 38,
        name: "Sistemas Operacionais",
        code: "CS303",
        instructor: "Prof. Leonardo Silva",
        credits: 3,
        schedule: "Qua/Sex 15:00",
        grade: 82,
        lastActivity: "Ontem",
      },
      {
        id: 39,
        name: "Computação em Nuvem",
        code: "CS304",
        instructor: "Dra. Amanda Santos",
        credits: 3,
        schedule: "Seg/Sex 14:00",
        grade: 80,
        lastActivity: "3 dias atrás",
      },
    ],
  },
  {
    id: "1012",
    name: "Camila Rodrigues",
    email: "camila.rodrigues@example.com",
    phone: "(555) 234-5678",
    program: "Engenharia de Software",
    yearLevel: "4º Ano",
    enrollmentDate: "1 Set, 2021",
    creditsCompleted: 102,
    academicStanding: "Lista do Reitor",
    advisor: "Dra. Vanessa Martins",
    attendance: 94,
    assignmentCompletion: 96,
    averageGrade: 90,
    riskLevel: "low",
    lastLogin: "Hoje",
    courses: [
      {
        id: 40,
        name: "Qualidade de Software",
        code: "SE401",
        instructor: "Dr. Rodrigo Alves",
        credits: 3,
        schedule: "Seg/Qua 9:00",
        grade: 92,
        lastActivity: "Hoje",
      },
      {
        id: 41,
        name: "DevOps",
        code: "SE402",
        instructor: "Prof. Daniel Costa",
        credits: 3,
        schedule: "Ter/Qui 14:00",
        grade: 88,
        lastActivity: "Ontem",
      },
      {
        id: 42,
        name: "Arquiteturas Avançadas",
        code: "SE403",
        instructor: "Dra. Luciana Ferreira",
        credits: 4,
        schedule: "Qua/Sex 11:00",
        grade: 91,
        lastActivity: "Hoje",
      },
      {
        id: 43,
        name: "Projeto Final de Engenharia",
        code: "SE499",
        instructor: "Dr. Gustavo Santos",
        credits: 5,
        schedule: "Sex 14:00",
        grade: 93,
        lastActivity: "Ontem",
      },
    ],
  },
  {
    id: "1013",
    name: "Bruno Oliveira",
    email: "bruno.oliveira@example.com",
    phone: "(555) 345-6789",
    program: "Ciência de Dados",
    yearLevel: "1º Ano",
    enrollmentDate: "1 Set, 2024",
    creditsCompleted: 14,
    academicStanding: "Boa Situação",
    advisor: "Dr. Ricardo Pereira",
    attendance: 68,
    assignmentCompletion: 60,
    averageGrade: 70,
    riskLevel: "high",
    lastLogin: "5 dias atrás",
    courses: [
      {
        id: 44,
        name: "Introdução à Ciência de Dados",
        code: "DS101",
        instructor: "Dra. Fernanda Costa",
        credits: 3,
        schedule: "Seg/Qua 11:00",
        grade: 65,
        lastActivity: "1 semana atrás",
      },
      {
        id: 45,
        name: "Estatística Básica",
        code: "STAT101",
        instructor: "Dr. Paulo Martins",
        credits: 4,
        schedule: "Ter/Qui 9:00",
        grade: 68,
        lastActivity: "5 dias atrás",
      },
      {
        id: 46,
        name: "Programação em Python",
        code: "DS102",
        instructor: "Profa. Carla Silva",
        credits: 3,
        schedule: "Qua/Sex 13:00",
        grade: 72,
        lastActivity: "6 dias atrás",
      },
      {
        id: 47,
        name: "Matemática para Ciência de Dados",
        code: "MATH201",
        instructor: "Dr. André Lima",
        credits: 4,
        schedule: "Seg/Sex 15:00",
        grade: 67,
        lastActivity: "4 dias atrás",
      },
    ],
  },
  {
    id: "1014",
    name: "Fernanda Lima",
    email: "fernanda.lima@example.com",
    phone: "(555) 456-7890",
    program: "Sistemas de Informação",
    yearLevel: "2º Ano",
    enrollmentDate: "1 Set, 2023",
    creditsCompleted: 40,
    academicStanding: "Boa Situação",
    advisor: "Dr. Marcos Oliveira",
    attendance: 82,
    assignmentCompletion: 78,
    averageGrade: 80,
    riskLevel: "medium",
    lastLogin: "2 dias atrás",
    courses: [
      {
        id: 48,
        name: "Redes de Computadores",
        code: "SI205",
        instructor: "Dr. Lucas Ferreira",
        credits: 3,
        schedule: "Seg/Qua 13:00",
        grade: 85,
        lastActivity: "2 dias atrás",
      },
      {
        id: 49,
        name: "Engenharia de Requisitos",
        code: "SI206",
        instructor: "Profa. Mariana Alves",
        credits: 3,
        schedule: "Ter/Qui 10:00",
        grade: 78,
        lastActivity: "3 dias atrás",
      },
      {
        id: 50,
        name: "Sistemas Empresariais",
        code: "SI207",
        instructor: "Dr. Roberto Santos",
        credits: 4,
        schedule: "Qua/Sex 14:00",
        grade: 75,
        lastActivity: "Ontem",
      },
      {
        id: 51,
        name: "Ética em TI",
        code: "SI208",
        instructor: "Dra. Juliana Costa",
        credits: 2,
        schedule: "Sex 9:00",
        grade: 82,
        lastActivity: "2 dias atrás",
      },
    ],
  },
  {
    id: "1015",
    name: "Gustavo Santos",
    email: "gustavo.santos@example.com",
    phone: "(555) 567-8901",
    program: "Engenharia da Computação",
    yearLevel: "3º Ano",
    enrollmentDate: "1 Set, 2022",
    creditsCompleted: 72,
    academicStanding: "Boa Situação",
    advisor: "Dra. Patrícia Oliveira",
    attendance: 88,
    assignmentCompletion: 84,
    averageGrade: 83,
    riskLevel: "low",
    lastLogin: "Ontem",
    courses: [
      {
        id: 52,
        name: "Microprocessadores",
        code: "EC301",
        instructor: "Dr. Felipe Costa",
        credits: 4,
        schedule: "Seg/Qua 10:00",
        grade: 85,
        lastActivity: "Ontem",
      },
      {
        id: 53,
        name: "Sistemas Embarcados",
        code: "EC302",
        instructor: "Prof. Rafael Silva",
        credits: 4,
        schedule: "Ter/Qui 13:00",
        grade: 80,
        lastActivity: "2 dias atrás",
      },
      {
        id: 54,
        name: "Processamento Digital de Sinais",
        code: "EC303",
        instructor: "Dra. Carolina Martins",
        credits: 3,
        schedule: "Qua/Sex 15:00",
        grade: 82,
        lastActivity: "Ontem",
      },
      {
        id: 55,
        name: "Robótica",
        code: "EC304",
        instructor: "Dr. Thiago Almeida",
        credits: 3,
        schedule: "Seg/Sex 14:00",
        grade: 86,
        lastActivity: "3 dias atrás",
      },
    ],
  },
]

export async function GET(request: Request, { params }: { params: { id: string } }) {
  const id = params.id

  // Encontra aluno por ID
  const student = studentsDetailed.find((s) => s.id === id)

  if (!student) {
    return NextResponse.json({ error: `Aluno com ID ${id} não encontrado` }, { status: 404 })
  }

  // Simula atraso da API
  await new Promise((resolve) => setTimeout(resolve, 800))

  return NextResponse.json(student)
}
